steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/salon-flow-owner:$SHORT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/salon-flow-owner:$SHORT_SHA'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'salon-flow-owner'
      - '--image'
      - 'gcr.io/$PROJECT_ID/salon-flow-owner:$SHORT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/salon-flow-owner:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
