module.exports = {
  ci: {
    collect: {
      url: ['http://localhost:3000'],
      numberOfRuns: 3,
      startServerCommand: 'npm run preview',
      startServerReadyPattern: 'Local:',
      startServerReadyTimeout: 60000,
      settings: {
        preset: 'desktop',
        throttling: {
          rttMs: 40,
          throughputKbps: 10240,
          cpuSlowdownMultiplier: 1,
        },
        screenEmulation: {
          mobile: false,
          width: 1350,
          height: 940,
          deviceScaleFactor: 1,
          disabled: false,
        },
        formFactor: 'desktop',
      },
    },
    assert: {
      assertions: {
        'categories:performance': ['error', { minScore: 0.9 }],
        'categories:accessibility': ['error', { minScore: 0.95 }],
        'categories:best-practices': ['error', { minScore: 0.95 }],
        'categories:seo': ['error', { minScore: 1.0 }],
        'categories:pwa': ['warn', { minScore: 0.9 }],
        
        // Core Web Vitals
        'first-contentful-paint': ['error', { maxNumericValue: 1800 }],
        'largest-contentful-paint': ['error', { maxNumericValue: 2500 }],
        'cumulative-layout-shift': ['error', { maxNumericValue: 0.1 }],
        'total-blocking-time': ['error', { maxNumericValue: 200 }],
        'interactive': ['error', { maxNumericValue: 3500 }],
        'speed-index': ['error', { maxNumericValue: 3400 }],
        
        // Resource budgets
        'resource-summary:document:size': ['error', { maxNumericValue: 50000 }],
        'resource-summary:script:size': ['error', { maxNumericValue: 500000 }],
        'resource-summary:stylesheet:size': ['error', { maxNumericValue: 100000 }],
        'resource-summary:image:size': ['warn', { maxNumericValue: 1000000 }],
        'resource-summary:font:size': ['warn', { maxNumericValue: 500000 }],
        'resource-summary:total:size': ['error', { maxNumericValue: 3000000 }],
        
        // Performance diagnostics
        'unused-javascript': ['warn', { maxNumericValue: 100000 }],
        'unused-css-rules': ['warn', { maxNumericValue: 50000 }],
        'modern-image-formats': ['error', { minScore: 1 }],
        'offscreen-images': ['error', { minScore: 1 }],
        'render-blocking-resources': ['error', { maxNumericValue: 0 }],
        'unminified-javascript': ['error', { minScore: 1 }],
        'unminified-css': ['error', { minScore: 1 }],
        'uses-text-compression': ['error', { minScore: 1 }],
        'uses-responsive-images': ['error', { minScore: 1 }],
        'efficiently-encode-images': ['error', { minScore: 1 }],
        'uses-optimized-images': ['error', { minScore: 1 }],
        'uses-long-cache-ttl': ['error', { minScore: 1 }],
        'total-byte-weight': ['error', { maxNumericValue: 2000000 }],
        'dom-size': ['error', { maxNumericValue: 1500 }],
        'no-document-write': ['error', { minScore: 1 }],
        'external-anchors-use-rel-noopener': ['error', { minScore: 1 }],
        'geolocation-on-start': ['error', { minScore: 1 }],
        'notification-on-start': ['error', { minScore: 1 }],
        'no-vulnerable-libraries': ['error', { minScore: 1 }],
        'password-inputs-can-be-pasted-into': ['error', { minScore: 1 }],
        'image-aspect-ratio': ['error', { minScore: 1 }],
        'image-size-responsive': ['error', { minScore: 1 }],
        'preload-fonts': ['warn', { minScore: 1 }],
        'legacy-javascript': ['warn', { maxNumericValue: 0 }],
        'mainthread-work-breakdown': ['error', { maxNumericValue: 350 }],
        'bootup-time': ['error', { maxNumericValue: 2000 }],
        'uses-rel-preload': ['warn', { minScore: 1 }],
        'uses-rel-preconnect': ['warn', { minScore: 1 }],
        'font-display': ['error', { minScore: 1 }],
        'third-party-summary': ['warn', { maxNumericValue: 500000 }],
        'third-party-facades': ['warn', { minScore: 1 }],
        'lcp-lazy-loaded': ['error', { minScore: 1 }],
        'duplicate-javascript': ['error', { minScore: 1 }],
        'no-unload-listeners': ['error', { minScore: 1 }],
        'non-composited-animations': ['warn', { minScore: 1 }],
        'unsized-images': ['error', { minScore: 1 }],
        'viewport': ['error', { minScore: 1 }],
        'uses-passive-event-listeners': ['error', { minScore: 1 }],
        'aria-allowed-attr': ['error', { minScore: 1 }],
        'aria-required-attr': ['error', { minScore: 1 }],
        'aria-required-children': ['error', { minScore: 1 }],
        'aria-required-parent': ['error', { minScore: 1 }],
        'aria-roles': ['error', { minScore: 1 }],
        'aria-valid-attr-value': ['error', { minScore: 1 }],
        'aria-valid-attr': ['error', { minScore: 1 }],
        'button-name': ['error', { minScore: 1 }],
        'bypass': ['error', { minScore: 1 }],
        'color-contrast': ['error', { minScore: 1 }],
        'definition-list': ['error', { minScore: 1 }],
        'dlitem': ['error', { minScore: 1 }],
        'document-title': ['error', { minScore: 1 }],
        'duplicate-id-active': ['error', { minScore: 1 }],
        'duplicate-id-aria': ['error', { minScore: 1 }],
        'form-field-multiple-labels': ['error', { minScore: 1 }],
        'frame-title': ['error', { minScore: 1 }],
        'heading-order': ['error', { minScore: 1 }],
        'html-has-lang': ['error', { minScore: 1 }],
        'html-lang-valid': ['error', { minScore: 1 }],
        'image-alt': ['error', { minScore: 1 }],
        'input-image-alt': ['error', { minScore: 1 }],
        'label': ['error', { minScore: 1 }],
        'link-name': ['error', { minScore: 1 }],
        'list': ['error', { minScore: 1 }],
        'listitem': ['error', { minScore: 1 }],
        'meta-viewport': ['error', { minScore: 1 }],
        'object-alt': ['error', { minScore: 1 }],
        'tabindex': ['error', { minScore: 1 }],
        'td-headers-attr': ['error', { minScore: 1 }],
        'th-has-data-cells': ['error', { minScore: 1 }],
        'valid-lang': ['error', { minScore: 1 }],
        'video-caption': ['error', { minScore: 1 }],
        'video-description': ['error', { minScore: 1 }],
        'custom-controls-labels': ['warn', { minScore: 1 }],
        'custom-controls-roles': ['warn', { minScore: 1 }],
        'focus-traps': ['error', { minScore: 1 }],
        'focusable-controls': ['error', { minScore: 1 }],
        'interactive-element-affordance': ['error', { minScore: 1 }],
        'logical-tab-order': ['error', { minScore: 1 }],
        'managed-focus': ['error', { minScore: 1 }],
        'offscreen-content-hidden': ['error', { minScore: 1 }],
        'use-landmarks': ['warn', { minScore: 1 }],
        'visual-order-follows-dom': ['error', { minScore: 1 }],
        'http-status-code': ['error', { minScore: 1 }],
        'is-crawlable': ['error', { minScore: 1 }],
        'robots-txt': ['error', { minScore: 1 }],
        'canonical': ['error', { minScore: 1 }],
        'hreflang': ['error', { minScore: 1 }],
        'plugins': ['error', { minScore: 1 }],
        'structured-data': ['warn', { minScore: 1 }],
      },
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
};
