# =============================================================================
# Salon Flow API - Cloud Build Configuration for Cloud Run Deployment
# =============================================================================
# Trigger: Push to main branch or manual trigger
# Requirements:
#   - Cloud Build API enabled
#   - Cloud Run API enabled
#   - Artifact Registry API enabled
#   - Service account with appropriate permissions
# =============================================================================

substitutions:
  # Service configuration
  _SERVICE_NAME: salon-flow-api
  _REGION: asia-south1  # Mumbai region for cost optimization
  _MEMORY: 512Mi
  _CPU: 1
  _MIN_INSTANCES: '0'  # Scale to zero for cost savings
  _MAX_INSTANCES: '10'
  _TIMEOUT: '300'
  
  # Artifact Registry
  _ARTIFACT_REPO: salon-flow-images
  
  # Environment
  _ENVIRONMENT: production

steps:
  # ===========================================================================
  # Step 1: Build the container image
  # ===========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'services/api/Dockerfile.cloudrun'
      - 'services/api'
    waitFor: ['-']

  # ===========================================================================
  # Step 2: Push to Artifact Registry
  # ===========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}'
    waitFor: ['Build Image']

  # ===========================================================================
  # Step 3: Deploy to Cloud Run
  # ===========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--set-env-vars'
      - 'ENVIRONMENT=${_ENVIRONMENT},FIREBASE_PROJECT_ID=${PROJECT_ID}'
      - '--set-secrets'
      - 'GCP_JSON_KEY=gcp-json-key:latest,OPENROUTER_API_KEY=openrouter-api-key:latest,UPSTASH_REDIS_URL=upstash-redis-url:latest'
      - '--no-allow-unauthenticated'
      - '--ingress'
      - 'all'
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:${_REGION}:salon-flow-db'
    waitFor: ['Push Image']

  # ===========================================================================
  # Step 4: Update traffic to latest revision
  # ===========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Update Traffic'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - '${_SERVICE_NAME}'
      - '--to-latest'
      - '--region'
      - '${_REGION}'
    waitFor: ['Deploy to Cloud Run']

  # ===========================================================================
  # Step 5: Run integration tests (optional)
  # ===========================================================================
  - name: 'python:3.11-slim'
    id: 'Health Check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y curl
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} --region ${_REGION} --format 'value(status.url)')
        echo "Service URL: $SERVICE_URL"
        for i in {1..30}; do
          if curl -s -f "$${SERVICE_URL}/health" -H "Authorization: Bearer $(gcloud auth print-identity-token)"; then
            echo "Health check passed!"
            exit 0
          fi
          echo "Attempt $i: Service not ready, waiting..."
          sleep 5
        done
        echo "Health check failed after 30 attempts"
        exit 1
    waitFor: ['Update Traffic']

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Build timeout
timeout: '1200s'

# Images to keep
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:latest'
